[tool.poetry]
name = "azure-function-distributed-tracing"
version = "0.1.0"
description = ""
authors = ["Jean-Baptiste Ranson <jranson@microsoft.com>", "Tamara Rahimi <tamararahimi@microsoft.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python =  ">=3.12,<3.13"
azure-functions = "^1.2.0"
azure-functions-durable = "^1.2.0"
black = "^24.0.0"
isort = "^5.13.0"
fastapi = "^0.115.0"
uvicorn = "^0.32.0"
requests = "^2.32.0"
azure-monitor-opentelemetry-exporter= ">=1.0.0b32,<2.0.0"
azure-core-tracing-opentelemetry= ">=1.0.0b11,<2.0.0"
opentelemetry-instrumentation-logging= ">=0.49b0,<1.0.0"
opentelemetry-instrumentation-aiohttp-client=">=0.49b0,<1.0.0"
opentelemetry-instrumentation-httpx=">=0.49b2,<1.0.0"
opentelemetry-instrumentation-requests=">=0.49b0,<1.0.0"
opentelemetry-instrumentation-urllib3=">=0.49b0,<1.0.0"
opentelemetry-instrumentation-fastapi=">=0.49b0,<1.0.0"
pip = "^24.3"
azure-monitor-opentelemetry = "^1.6.0"
azure-storage-queue = "^12.12.0"
azure-identity = "^1.19.0"
pydantic = "^2.8.2"
pydantic-settings = "^2.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
